export const HeroesListMock = [
  {
    id: 1,
    name: 'Aatrox',
    title: 'the Darkin Blade',
    tags: ['Fighter', 'Tank'],
    top: true,
    stats: {
      hp: 580,
      movespeed: 345,
      armor: 38,
      attackrange: 175,
      attackdamage: 60,
      attackspeed: 0.651,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Aatrox.png',
    description:
      'Once honored defenders of Shurima against the Void, Aatrox and his brethren would eventually become an even greater threat to Runeterra, and were defeated only by cunning mortal sorcery. But after centuries of imprisonment, Aatrox was the first to find...',
  },
  {
    id: 2,
    name: 'Ahri',
    title: 'the Nine-Tailed Fox',
    tags: ['Mage', 'Assassin'],
    top: false,
    stats: {
      hp: 526,
      movespeed: 330,
      armor: 20.88,
      attackrange: 550,
      attackdamage: 53.04,
      attackspeed: 0.668,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ahri.png',
    description:
      'Innately connected to the latent power of Runeterra, Ahri is a vastaya who can reshape magic into orbs of raw energy. She revels in toying with her prey by manipulating their emotions before devouring their life essence. Despite her predatory nature...',
  },
  {
    id: 3,
    name: 'Akali',
    title: 'the Rogue Assassin',
    tags: ['Assassin'],
    top: false,
    stats: {
      hp: 575,
      movespeed: 345,
      armor: 23,
      attackrange: 125,
      attackdamage: 62.4,
      attackspeed: 0.625,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Akali.png',
    description:
      'Abandoning the Kinkou Order and her title of the Fist of Shadow, Akali now strikes alone, ready to be the deadly weapon her people need. Though she holds onto all she learned from her master Shen, she has pledged to defend Ionia from its enemies, one...',
  },
  {
    id: 4,
    name: 'Blitzcrank',
    title: 'the Great Steam Golem',
    tags: ['Tank', 'Fighter'],
    top: false,
    stats: {
      hp: 582.6,
      movespeed: 325,
      armor: 37,
      attackrange: 125,
      attackdamage: 61.54,
      attackspeed: 0.625,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Blitzcrank.png',
    description:
      'Blitzcrank is an enormous, near-indestructible automaton from Zaun, originally built to dispose of hazardous waste. However, he found this primary purpose too restricting, and modified his own form to better serve the fragile people of the Sump...',
  },
  {
    id: 5,
    name: 'Camille',
    title: 'the Steel Shadow',
    tags: ['Fighter', 'Tank'],
    top: true,
    stats: {
      hp: 575.6,
      movespeed: 340,
      armor: 35,
      attackrange: 125,
      attackdamage: 68,
      attackspeed: 0.644,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Camille.png',
    description:
      'Weaponized to operate outside the boundaries of the law, Camille is the Principal Intelligencer of Clan Ferros—an elegant and elite agent who ensures the Piltover machine and its Zaunite underbelly runs smoothly. Adaptable and precise, she views sloppy...',
  },
  {
    id: 6,
    name: 'Draven',
    title: 'the Glorious Executioner',
    tags: ['Marksman'],
    top: false,
    stats: {
      hp: 605,
      movespeed: 330,
      armor: 29,
      attackrange: 550,
      attackdamage: 60,
      attackspeed: 0.679,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Draven.png',
    description:
      'In Noxus, warriors known as Reckoners face one another in arenas where blood is spilled and strength tested—but none has ever been as celebrated as Draven. A former soldier, he found that the crowds uniquely appreciated his flair for the dramatic, and...',
  },
  {
    id: 7,
    name: 'Ezreal',
    title: 'the Prodigal Explorer',
    tags: ['Marksman', 'Mage'],
    top: false,
    stats: {
      hp: 530,
      movespeed: 325,
      armor: 22,
      attackrange: 550,
      attackdamage: 60,
      attackspeed: 0.625,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ezreal.png',
    description:
      'A dashing adventurer, unknowingly gifted in the magical arts, Ezreal raids long-lost catacombs, tangles with ancient curses, and overcomes seemingly impossible odds with ease. His courage and bravado knowing no bounds, he prefers to improvise his way...',
  },
  {
    id: 8,
    name: 'Gangplank',
    title: 'the Saltwater Scourge',
    tags: ['Fighter'],
    top: false,
    stats: {
      hp: 540,
      movespeed: 345,
      armor: 35,
      attackrange: 125,
      attackdamage: 64,
      attackspeed: 0.658,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gangplank.png',
    description:
      'As unpredictable as he is brutal, the dethroned reaver king Gangplank is feared far and wide. Once, he ruled the port city of Bilgewater, and while his reign is over, there are those who believe this has only made him more dangerous. Gangplank would see...',
  },
  {
    id: 9,
    name: 'Heimerdinger',
    title: 'the Revered Inventor',
    tags: ['Mage', 'Support'],
    top: false,
    stats: {
      hp: 488,
      movespeed: 340,
      armor: 19.04,
      attackrange: 550,
      attackdamage: 55.536,
      attackspeed: 0.625,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Heimerdinger.png',
    description:
      "A brilliant yet eccentric yordle scientist, Professor Cecil B. Heimerdinger is one of the most innovative and esteemed inventors Piltover has ever known. Relentless in his work to the point of neurotic obsession, he thrives on answering the universe's...",
  },
  {
    id: 10,
    name: 'Jarvan IV',
    title: 'the Exemplar of Demacia',
    tags: ['Tank', 'Fighter'],
    top: true,
    stats: {
      hp: 570,
      movespeed: 340,
      armor: 34,
      attackrange: 175,
      attackdamage: 64,
      attackspeed: 0.658,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/JarvanIV.png',
    description:
      "Prince Jarvan, scion of the Lightshield dynasty, is heir apparent to the throne of Demacia. Raised to be a paragon of his nation's greatest virtues, he is forced to balance the heavy expectations placed upon him with his own desire to fight on the front...",
  },
  {
    id: 11,
    name: 'Yasuo',
    title: 'the Unforgiven Inter',
    tags: ['Fighter', 'Assassin'],
    top: false,
    stats: {
      hp: 490,
      movespeed: 345,
      armor: 30,
      attackrange: 175,
      attackdamage: 60,
      attackspeed: 0.697,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yasuo.png',
    description:
      'An Ionian of deep resolve, Yasuo is an agile inter who wields the air itself against his enemies. As a proud young man, he was falsely accused of murdering his master—unable to prove his innocence, he was forced to slay his own brother in self...',
  },
  {
    id: 12,
    name: 'Yuumi',
    title: 'the Magical Cat',
    tags: ['Support', 'Mage'],
    top: true,
    stats: {
      hp: 480,
      movespeed: 330,
      armor: 25,
      attackrange: 500,
      attackdamage: 55,
      attackspeed: 0.625,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yuumi.png',
    description:
      "A magical cat from Bandle City, Yuumi was once the familiar of a yordle enchantress, Norra. When her master mysteriously disappeared, Yuumi became the Keeper of Norra's sentient Book of Thresholds, traveling through portals in its pages to search for...",
  },
  {
    id: 13,
    name: 'Zed',
    title: 'the Master of Shadows',
    tags: ['Assassin'],
    top: false,
    stats: {
      hp: 584,
      movespeed: 345,
      armor: 32,
      attackrange: 125,
      attackdamage: 63,
      attackspeed: 0.651,
    },
    icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zed.png',
    description:
      "Utterly ruthless and without mercy, Zed is the leader of the Order of Shadow, an organization he created with the intent of militarizing Ionia's magical and martial traditions to drive out Noxian invaders. During the war, desperation led him to unlock...",
  },
];
